CREATE TABLE IF NOT EXISTS POSTS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMMENTS(
    id INT PRIMARY KEY AUTO_INCREMENT,
    body VARCHAR(200),
    email VARCHAR(200),
    name VARCHAR(200),
    postid INT,
    foreign key (postid) references POSTS(id)
);

CREATE TABLE IF NOT EXISTS USERS(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200),
    username VARCHAR(200),
    email VARCHAR(200),
    password VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS ROLES(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200)
);